project:
  type: book
execute:
  cache: true
  freeze: auto
book:
  
  google-analytics: "G-5T7SZYQV79"
  title: "R4PDE"
  author: "Emerson M. Del Ponte"
  search: true
  repo-url: https://github.com/emdelponte/epidemiology-R
  cover-image: cover.png
  repo-actions: [edit, issue]
  page-footer: 
    border: false
    background: light
    left: | 
      R for Plant Disease Epidemiology is written by Emerson Del Ponte
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
    
  chapters:
    - index.qmd
    - author.qmd
    - intro.qmd
    - part: "Epidemic data"
      chapters:
        - data-terminology.qmd
        - data-ordinal.qmd
        - data-actual-severity.qmd
        - data-accuracy.qmd
        - data-sads.qmd
        - data-training.qmd
        
        
    - part: "Temporal analysis"
      chapters: 
        - temporal-dpc.qmd
        - temporal-models.qmd
        - temporal-fitting.qmd
    - part: "Spatial analysis"
      chapters:
        - spatial-gradients.qmd
        - spatial-models.qmd
        - spatial-fitting.qmd
        - spatial-patterns.qmd
        - spatial-tests.qmd
    - part: "Epidemics and yield"
      chapters:
        - yieldloss-concepts.qmd
        - yieldloss-regression-models.qmd
    - references.qmd


bibliography: references.bib
csl: phytopathology.csl
prefer-html: true
format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: 
        - flatly
        - r4pd.scss
        #- custom.scss
      dark: 
        - darkly
  pdf:
    title: "R for Plant Disease Epidemiology"
    toc: true
    documentclass: book
    geometry:
      - paperwidth=8.00in
      - paperheight=10.00in
      - left=1.25in
      - textwidth= 5.25in
      - top=1.00in
      - textheight=8.25in
    number-sections: true
    colorlinks: true
    fig-width: 5
    fig-height: 5
    fig-align: left
    keep-tex: true
  epub:
    epub-cover-image: cover.png



